version: '3'

services:
  db:
    container_name: django_chat_app-db
    image: postgres
    environment:
      - POSTGRES_DB=chat_system

  web:
    container_name: django-chat-app-web
    build: .
    volumes:
      - .:/django-chat-app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db      